version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: stackit-postgres
    environment:
      POSTGRES_DB: stackit_db
      POSTGRES_USER: stackit_user
      POSTGRES_PASSWORD: stackit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - stackit-network

  # Backend API
  backend:
    build: ./backend
    container_name: stackit-backend
    environment:
      DATABASE_URL: postgresql://stackit_user:stackit_password@postgres:5432/stackit_db
      NODE_ENV: production
      PORT: 3001
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - stackit-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: stackit-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - stackit-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  stackit-network:
    driver: bridge